### ISSUE TITLE
Sort agent and agentprocess tables by default

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-dashboard#111] opened 2020-11-20 12:35 UTC
**Problem:**

The agent and agent process tables in the agents tab of the dashboard don't sort the rows in a logical way by default.

**Comment by bartv** [comment] 2021-01-27 08:17
The code does sort. This was caused by the order bug which is now fixed in core.

**Closed by bartv** 2021-01-27 08:17 UTC
Labels: enhancement
